# Run this file only to create the topics after running docker-compose-kafka.yml
# To run: docker-compose -p food-ordering-kafka -f docker-compose-common.yml -f docker-compose-kafka.yml up -d
version: '3.7'
services:
  init-kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION:-latest}
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      # block until kafka broker is ready
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list
      
      echo -e 'Deleting existing kafka topics (if exist)'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --delete --if-exists --topic payment-request
      kafka-topics --bootstrap-server kafka-broker-1:9092 --delete --if-exists --topic payment-response
      kafka-topics --bootstrap-server kafka-broker-1:9092 --delete --if-exists --topic restaurant-approval-request
      kafka-topics --bootstrap-server kafka-broker-1:9092 --delete --if-exists --topic restaurant-approval-response

      echo -e 'Creating kafka topics (if not exist)'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic payment-request --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic payment-response --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic restaurant-approval-request --replication-factor 1 --partitions 3
      kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic restaurant-approval-response --replication-factor 1 --partitions 3
      
      echo -e 'Successfully created the following kafka topics'
      kafka-topics --bootstrap-server kafka-broker-1:9092 --list      
      "
    networks:
      - ${GLOBAL_NETWORK:-kafka}
